# =============================================================================
# VENDORED - do not edit by hand.
#
# Generated by : tools/vendor.py
# Source details are intentionally omitted for non-public inputs.
# Tool   : tools/vendor.py
#
# Re-run ``python tools/vendor.py sync`` to update this file, and
# ``python tools/vendor.py check`` to detect drift against its source.
#
# Only ``import`` statements were rewritten; every numeric expression is
# byte-identical to the source.  Edits belong upstream, or in a devkit module
# that wraps this one.
# =============================================================================

"""``normalize_angle`` vendored from navsim pdm_geometry_utils."""

import numpy as np
import numpy.typing as npt


def normalize_angle(angle: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
    """Map an angle to [-pi, pi)."""
    return (angle + np.pi) % (2 * np.pi) - np.pi
