# =============================================================================
# VENDORED - do not edit by hand.
#
# Generated by : tools/vendor.py
# Source details are intentionally omitted for non-public inputs.
# Tool   : tools/vendor.py
#
# Re-run ``python tools/vendor.py sync`` to update this file, and
# ``python tools/vendor.py check`` to detect drift against its source.
#
# Only ``import`` statements were rewritten; every numeric expression is
# byte-identical to the source.  Edits belong upstream, or in a devkit module
# that wraps this one.
# =============================================================================

"""Minimal stand-ins for the nuplan value types the vendored files import."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class VehicleParameters:
    """Only the fields the tracker/motion model read."""

    wheel_base: float
    width: float
    front_length: float = 0.0
    rear_length: float = 0.0
    length: float = 0.0


def get_pacifica_parameters() -> VehicleParameters:
    """navsim's default vehicle (nuplan's Pacifica) — kept so the vendored
    default arguments resolve; real calls pass the ego's own parameters."""
    return VehicleParameters(wheel_base=3.089, width=2.297, length=5.176)


@dataclass(frozen=True)
class TimePoint:
    time_us: int

    @property
    def time_s(self) -> float:
        return self.time_us * 1e-6

    def __add__(self, other: "TimeDuration") -> "TimePoint":
        return TimePoint(self.time_us + other.time_us)

    def __sub__(self, other: "TimePoint") -> "TimeDuration":
        return TimeDuration(self.time_us - other.time_us)


@dataclass(frozen=True)
class TimeDuration:
    time_us: int

    @property
    def time_s(self) -> float:
        return self.time_us * 1e-6

    @classmethod
    def from_s(cls, seconds: float) -> "TimeDuration":
        return cls(int(round(seconds * 1e6)))


@dataclass(frozen=True)
class SimulationIteration:
    time_point: TimePoint
    index: int


def principal_value(angle):
    """Wrap to (-pi, pi] — nuplan's helper of the same name."""
    return np.arctan2(np.sin(angle), np.cos(angle))
