# =============================================================================
# VENDORED - do not edit by hand.
#
# Generated by : tools/vendor.py
# Source details are intentionally omitted for non-public inputs.
# Tool   : tools/vendor.py
#
# Re-run ``python tools/vendor.py sync`` to update this file, and
# ``python tools/vendor.py check`` to detect drift against its source.
#
# Only ``import`` statements were rewritten; every numeric expression is
# byte-identical to the source.  Edits belong upstream, or in a devkit module
# that wraps this one.
# =============================================================================

"""navsim's ``PDMSimulator.simulate_proposals``, ported to our inputs.

The loop is line-for-line ``pdm_simulator.py`` (lines 45-78); only the entry
points differ: navsim starts from an ``EgoState`` object, we start from the
batch's ``ego_current_state`` and ``ego_shape``.
"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt

from t4_e2e_devkit.planning.simulation.pdm_sim.batch_kinematic_bicycle import BatchKinematicBicycleModel
from t4_e2e_devkit.planning.simulation.pdm_sim.batch_lqr import BatchLQRTracker
from t4_e2e_devkit.planning.simulation.pdm_sim.enums import StateIndex
from t4_e2e_devkit.planning.simulation.pdm_sim.nuplan_stubs import (
    SimulationIteration,
    TimeDuration,
    TimePoint,
    VehicleParameters,
)

STATE_SIZE = 11  # len(StateIndex): x, y, heading, vx, vy, ax, ay, steer, steer_rate, w, dw


def states_from_trajectory(
    poses: npt.NDArray[np.float64],
    initial_velocity: npt.NDArray[np.float64],
) -> npt.NDArray[np.float64]:
    """Build navsim's state array from ``[B, T, 3]`` (x, y, heading) poses.

    Only the fields the tracker reads are filled — ``BatchLQRTracker.update``
    consumes ``STATE_SE2`` and re-derives velocity/curvature itself from the
    pose sequence (its jerk-penalised least-squares fit), so seeding anything
    else would be ignored.
    """
    poses = np.asarray(poses, dtype=np.float64)
    b, t, _ = poses.shape
    states = np.zeros((b, t, STATE_SIZE), dtype=np.float64)
    states[..., StateIndex.X] = poses[..., 0]
    states[..., StateIndex.Y] = poses[..., 1]
    states[..., StateIndex.HEADING] = poses[..., 2]
    states[:, 0, StateIndex.VELOCITY_X] = np.asarray(initial_velocity, dtype=np.float64)
    return states


def simulate_proposals(
    poses: npt.NDArray[np.float64],
    initial_velocity: npt.NDArray[np.float64],
    wheel_base: float | npt.NDArray[np.float64],
    dt: float = 0.1,
    width: float = 1.7,
) -> npt.NDArray[np.float64]:
    """Track ``poses`` with the LQR controller through the bicycle model.

    :param poses: ``[B, T, 3]`` planned (x, y, heading) in a consistent frame.
    :param initial_velocity: ``[B]`` ego speed at t0 (m/s).
    :param wheel_base: metres; a scalar (batch shares a vehicle) — the vendored
        tracker takes one vehicle for the batch, so a per-sample wheel base
        must be simulated in separate calls.
    :return: ``[B, T, STATE_SIZE]`` simulated states, the array navsim feeds to
        ``ego_is_comfortable``.
    """
    poses = np.asarray(poses, dtype=np.float64)
    if poses.ndim != 3 or poses.shape[-1] != 3:
        raise ValueError(f"poses must be [B, T, 3], got {poses.shape}")
    wb = float(np.asarray(wheel_base).reshape(-1)[0])
    vehicle = VehicleParameters(wheel_base=wb, width=float(width))

    tracker = BatchLQRTracker(discretization_time=dt, vehicle=vehicle)
    motion_model = BatchKinematicBicycleModel(vehicle=vehicle)
    tracker._discretization_time = dt

    proposal_states = states_from_trajectory(poses, initial_velocity)
    tracker.update(proposal_states)

    simulated = np.zeros_like(proposal_states)
    simulated[:, 0] = proposal_states[:, 0]  # start ON the plan, as navsim does

    delta = TimeDuration.from_s(dt)
    current = SimulationIteration(TimePoint(0), 0)
    nxt = SimulationIteration(TimePoint(0) + delta, 1)
    for time_idx in range(1, poses.shape[1]):
        sampling_time = nxt.time_point - current.time_point
        command_states = tracker.track_trajectory(current, nxt, simulated[:, time_idx - 1])
        simulated[:, time_idx] = motion_model.propagate_state(
            states=simulated[:, time_idx - 1],
            command_states=command_states,
            sampling_time=sampling_time,
        )
        current = nxt
        nxt = SimulationIteration(current.time_point + delta, 1 + time_idx)
    return simulated
